version: '3'

services:
  postgres:
    image: postgres
    ports:
      - "10000:5432"
    environment:
      POSTGRES_PASSWORD: mew
    volumes:
      - ./postgree/:/postgree/
      - ./postgree-updated:/var/lib/postgresql/data

  neo4j2:
    image: neo4j:4.0.0
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j-updated2:/data
